services:
  postgres:
    image: postgres:17.5
    container_name: postgres17
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev1234
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: